version: '2'
services:
  border-crossings:
    container_name: border-crossings
    build:
      context: .
      dockerfile: Dockerfile
    image: border-crossings:latest
    ports:
      - 8080:8080
    depends_on:
      - mongo-db
      - redis-db
  mongo-db:
    container_name: 'mongo-db'
    image: 'mongo:3.3'
    command: '--port 27018 --storageEngine wiredTiger'
    ports:
      - '27018:27018'
    volumes:
      - 'mongodata:/data/db'

  redis-db:
    container_name: 'redis-db'
    image: 'redis:3.2.0'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  mongodata:
  redisdata: